apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
spec:
  selector:
    matchLabels:
      name: ibm-platform-api-operator
  replicas: 1
  template:
    metadata:
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
      labels:
        app.kubernetes.io/instance: platform-api
        app.kubernetes.io/managed-by: platformapis.operator.ibm.com
        app.kubernetes.io/name: platformapis.operator.ibm.com
        name: ibm-platform-api-operator
    spec:
      serviceAccountName: ibm-platform-api-operator
      containers:
      - image: quay.io/opencloudio/ibm-platform-api-operator:dev
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERAND_AUDIT_SERVICE_IMAGE
            value: "quay.io/opencloudio/audit-syslog-service@sha256:1466c23e64e2dddf68374c6997dec8bb1d3054d1a620e059ed5ff168887e95cc"
          - name: OPERAND_PLATFORM_API_IMAGE
            value: "quay.io/opencloudio/icp-platform-api@sha256:a11df312d3c3e58ebcf1503df1c3eecaa122d706083930ba910179b6a47b30c7"           
        args:
        - "--enable-leader-election"
        - "--leader-election-id=ibm-platform-api-operator"
        name: ibm-platform-api-operator
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
