# If deploying the manifests directly, i.e. make deploy,
# the service account needs to be explicitly created.
# If deploying using OLM, then service account is created for you
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com