apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: ibm-common-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: ibm-platform-api-operator
      containers:
      - image: quay.io/opencloudio/ibm-platform-api-operator:3.8.0
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERAND_AUDIT_SERVICE_IMAGE
            value: "quay.io/opencloudio/audit-syslog-service@sha256:1466c23e64e2dddf68374c6997dec8bb1d3054d1a620e059ed5ff168887e95cc"
          - name: OPERAND_PLATFORM_API_IMAGE
            value: "quay.io/opencloudio/icp-platform-api@sha256:a95aa0fc5afc7a436f412ad6fa8c993d2d5a31844000ec24604d5345965e3cb9"           
        args:
        - "--enable-leader-election"
        - "--leader-election-id=ibm-platform-api-operator"
        name: ibm-platform-api-operator
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
