apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ibm-platform-api-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-platform-api-operator-role
subjects:
- kind: ServiceAccount
  name: ibm-platform-api-operator
  namespace: system
