---
apiVersion: batch/v1
kind: Job
metadata:
  name: "password-management-migration"
  labels:
    app: password-management-migration
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: password-management-migration
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name:  {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      labels:
        app: password-management-migration
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        k8s-app: password-management-migration
        component: password-management-migration
        release: {{ .Release.Name }}
        app.kubernetes.io/instance: password-management-migration
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: password-management-migration
        helm.sh/chart: {{ .Release.Name }}
    spec:
      serviceAccountName: ibm-platform-api-operand
      restartPolicy: Never
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: migration
      {{- if hasPrefix "sha256:" .Values.platformApi.image.digest }}
        image: "{{ .Values.platformApi.image.imageRegistry }}/{{ .Values.platformApi.image.name }}@{{ .Values.platformApi.image.digest }}"
      {{- else }}
        image: "{{ .Values.platformApi.image.imageRegistry }}/{{ .Values.platformApi.image.name }}:{{ .Values.platformApi.image.digest }}"
      {{- end }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: etcd-certs
          mountPath: /etc/etcd
        command:
        - /bin/sh
        - -c
        - |
          /usr/local/platform-api/bin/password-management.sh /etc/etcd
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: etcd-config
              key: etcd_endpoints
              optional: true
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
      volumes:
      - name: etcd-certs
        secret:
          secretName: {{ .Values.platformApi.config.etcdSecret }}
          optional: true
          items:
          - key: etcd-ca
            path: ca.pem
          - key: etcd-cert
            path: client.pem
          - key: etcd-key
            path: client-key.pem
{{- if .Values.platformApi.tolerations }}
      tolerations:
{{ toYaml .Values.platformApi.tolerations | indent 8 }}
    {{- end }}
