---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: platform-api-ca-cert
  labels:
    app: platform-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "platform-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  commonName: platform-api
  dnsNames:
  - platform-api
  - platform-api.{{ .Release.Namespace }}
  issuerRef:
    kind: Issuer
    name: cs-ca-issuer
  organization:
  - IBM
  secretName: "{{ .Values.platformApi.config.clusterCASecret }}"
