apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: platform-api-ca-cert
  namespace: {{ .Values.platformApi.namespace }}
spec:
  issuerRef:
    name: cs-ss-issuer
    kind: Issuer
  secretName: platform-api-ca-cert-secret
  commonName: ca-certificate
  isCA: true
