---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-platform-api-operand
  labels:
    name: ibm-platform-api-operand
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-platform-api-operand
  labels:
    name: ibm-platform-api-operand
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - get
      - list
  - apiGroups:
      - icp.ibm.com
    resources:
      - passwordrules
    verbs:
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-platform-api-operand
  labels:
    name: ibm-platform-api-operand
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - platformapis.operator.ibm.com
      - passwordrules.icp.ibm.com
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    resourceNames:
      - ibm-platform-api-operand
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-platform-api-operand
  labels:
    name: ibm-platform-api-operand
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: ibm-platform-api-operand
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-platform-api-operand
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-platform-api-operand
  labels:
    name: ibm-platform-api-operand
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: ibm-platform-api-operand
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-platform-api-operand
