# permissions for end users to edit platformapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformapi-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - platformapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - platformapis/status
  verbs:
  - get
