apiVersion: operator.ibm.com/v1alpha1
kind: PlatformAPI
metadata:
  name: platform-api
  annotations:
    helm.operator-sdk/upgrade-force: true
  labels:
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platform-api
spec:
  auditService:
    config:
      enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 250Mi
  platformApi:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  replicaCount: 1
  replicas: 1
  size: small
