apiVersion: operator.ibm.com/v1alpha1
kind: PlatformAPI
metadata:
  name: platform-api
  annotations:
    helm.operator-sdk/upgrade-force: "True"  
  labels:
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platform-api
spec:
  auditService:
    config:
      enabled: true
    image:
      imageRegistry: quay.io/opencloudio
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  platformApi:
    image:
      imageRegistry: quay.io/opencloudio
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  replicaCount: 1
