apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwordrules.operator.ibm.com
  labels:
    app.kubernetes.io/instance: passwordrule
    app.kubernetes.io/managed-by: passwordrules.operator.ibm.com
    app.kubernetes.io/name: passwordrules.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: PasswordRule
    listKind: PasswordRuleList
    plural: passwordrules
    singular: passwordrule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PasswordRule is the Schema for the passwordrule
      properties:
        apiVersion:
          description:
            'APIVersion defines the versioned schema of this representation of
            an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description:
            'Kind is a string value representing the REST resource this object
            represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          properties:
            description:
              type: string
            regex:
              type: string
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
