apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-platform-api-operator
  template:
    metadata:
      labels:
        name: ibm-platform-api-operator
        app.kubernetes.io/instance: platform-api
        app.kubernetes.io/managed-by: platformapis.operator.ibm.com
        app.kubernetes.io/name: platformapis.operator.ibm.com
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: ibm-platform-api-operator
      initContainers:
        - name: pre-install
          image: quay.io/opencloudio/kubectl@sha256:deeb798aaa12142c95ba37bd90ae99ed112afda1170be321db8b1476c7ac9fdd
          imagePullPolicy: IfNotPresent
          securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          resources:
            limits:
              cpu: "150m"
              memory: 128Mi
            requests:
              cpu: "150m"
              memory: 128Mi
          command:
          - sh
          - -c
          - |
            kubectl annotate platformapis --all helm.operator-sdk/upgrade-force-
      containers:
        - name: ibm-platform-api-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-platform-api-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-platform-api-operator"
            - name: OPERAND_AUDIT_SERVICE_IMAGE
              value: "quay.io/opencloudio/icp-audit-service@sha256:a649814564039ee923cb503720e9c5e87c20b3c340f06c48660490aeaed04d5a"
            - name: OPERAND_PLATFORM_API_IMAGE
              value: "quay.io/opencloudio/icp-platform-api@sha256:a764156e13addddb69d2ca9e3e2213bc518a71b8a32f1f76746e0bce932dff0b"          
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
