apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-platform-api-operator
  template:
    metadata:
      labels:
        name: ibm-platform-api-operator
        app.kubernetes.io/instance: platform-api
        app.kubernetes.io/managed-by: platformapis.operator.ibm.com
        app.kubernetes.io/name: platformapis.operator.ibm.com
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: FREE
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: ibm-platform-api-operator
      initContainers:
        - name: helm-force-upgrade-false
          image: quay.io/opencloudio/icp-platform-api@sha256:39aef36abb932c1f07423649f13c093063c38aa05d08b2378f986203a3299a58
          imagePullPolicy: Always
          securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          resources:
            limits:
              cpu: "150m"
              memory: 256Mi
            requests:
              cpu: "150m"
              memory: 256Mi
          command:
          - sh
          - -c
          - |
            kubectl -n ibm-common-services patch platformapis platform-api \
              --type json \
              -p='[{"op": "replace", "path": "/metadata/annotations/helm.operator-sdk~1upgrade-force", "value": "False"}]'
      containers:
        - name: ibm-platform-api-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-platform-api-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-platform-api-operator"
            - name: OPERAND_AUDIT_SERVICE_IMAGE
              value: "quay.io/opencloudio/icp-audit-service@sha256:24a220374c39652f8b031637d852995bfaec5be2601f9e4c41eb1925531f466d"
            - name: OPERAND_PLATFORM_API_IMAGE
              value: "quay.io/opencloudio/icp-platform-api@sha256:39aef36abb932c1f07423649f13c093063c38aa05d08b2378f986203a3299a58"          
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
