apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-platform-api-operator
subjects:
- kind: ServiceAccount
  name: ibm-platform-api-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-platform-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-platform-api-operator
subjects:
- kind: ServiceAccount
  name: ibm-platform-api-operator
  namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-platform-api-operator