---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    name: ibm-platform-api-operator
  name: ibm-platform-api-operator
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - deletecollection
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - ibm-platform-api-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - icp.ibm.com
    resources:
      - passwordrules
    verbs:
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.ibm.com
    resources:
      - platformapis
      - platformapis/finalizers
      - platformapis/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
    name: ibm-platform-api-operator
  name: ibm-platform-api-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - passwordrules.icp.ibm.com
      - platformapis.operator.ibm.com
    resources:
      - customresourcedefinitions
    verbs:
      - delete
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - ibm-platform-api-operator
      - ibm-platform-api-operand
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - delete
      - patch
      - update
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
