auditService:
  config:
    auditEnabled: false
    auditLogPath: /var/log/audit
    enabled: true
    logrotate: |-
      /var/log/audit/*.log {
        copytruncate
        rotate 24
        hourly
        missingok
        notifempty
      }
    logrotateConf: include /etc/logrotate.d
  image:
    pullPolicy: IfNotPresent
    imageRegistry: quay.io/opencloudio 
    repository: icp-audit-service
    tag: 3.4.0
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
platformApi:
  config:
    acctName: mycluster Account
    clusterCASecret: cs-ca-certificate-secret
    clusterCAdomain: mycluster.icp
    clusterExternalAddress: 127.0.0.1
    clusterInternalAddress: 127.0.0.1
    clusterName: mycluster
    clusterSecurePort: 443
    etcdSecret: etcd-secret
    kubeApiserverSecurePort: 6443
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    imageRegistry: quay.io/opencloudio
    repository: icp-platform-api
    tag: 3.4.0
  name: platform-api
  nodeSelector: {}
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
runAsUser: 65534
