auditService:
  config:
    auditLogPath: /var/log/audit
    enabled: true
    logrotate: |-
      /var/log/audit/*.log {
        copytruncate
        rotate 24
        hourly
        missingok
        notifempty
      }
    logrotateConf: include /etc/logrotate.d
  image:
    repository: quay.io/opencloudio/audit-syslog-service@sha256:1466c23e64e2dddf68374c6997dec8bb1d3054d1a620e059ed5ff168887e95cc
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi
platformApi:
  config:
    acctName: mycluster Account
    clusterCASecret: cs-ca-certificate-secret
    clusterCAdomain: mycluster.icp
    clusterExternalAddress: 127.0.0.1
    clusterInternalAddress: 127.0.0.1
    clusterName: mycluster
    clusterSecurePort: 443
    etcdSecret: etcd-secret
    kubeApiserverSecurePort: 6443
  hostNetwork: false
  image:
    repository: quay.io/opencloudio/icp-platform-api@sha256:a7cb08c4bf808a4f3877c35d50ccb4a2052f77952bc0794dd8a83df63f981385
    pullPolicy: IfNotPresent
  name: platform-api
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
replicaCount: 1
# replicas: 1
runAsUser: 65534
