auditService:
  config:
    auditLogPath: /var/log/audit
    enabled: true
    logrotate: |-
      /var/log/audit/*.log {
        copytruncate
        rotate 24
        hourly
        missingok
        notifempty
      }
    logrotateConf: include /etc/logrotate.d
  image:
    repository: quay.io/opencloudio/icp-audit-service@sha256:24a220374c39652f8b031637d852995bfaec5be2601f9e4c41eb1925531f466d
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi
platformApi:
  config:
    acctName: mycluster Account
    clusterCASecret: cs-ca-certificate-secret
    clusterCAdomain: mycluster.icp
    clusterExternalAddress: 127.0.0.1
    clusterInternalAddress: 127.0.0.1
    clusterName: mycluster
    clusterSecurePort: 443
    etcdSecret: etcd-secret
    kubeApiserverSecurePort: 6443
  hostNetwork: false
  image:
    repository: quay.io/opencloudio/icp-platform-api@sha256:39aef36abb932c1f07423649f13c093063c38aa05d08b2378f986203a3299a58
    pullPolicy: IfNotPresent
  name: platform-api
  namespace: "ibm-common-services"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
replicaCount: 1
runAsUser: 65534
