apiVersion: operator.ibm.com/v1alpha1
kind: PlatformAPI
metadata:
  labels:
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platform-api
  name: platform-api
spec:
  auditService:
    config:
      enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 250Mi
  platformApi:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  replicas: 1
