apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: passwordrules.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: PasswordRule
    listKind: PasswordRuleList
    plural: passwordrules
    singular: passwordrule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            description:
              type: string
            regex:
              type: string
  versions:
  - name: v1alpha1
    served: true
    storage: true